### ISSUE TITLE
[BUG]  Import "buf/validate/validate.proto" was not found or had errors

### ISSUE THREAD

**Issue by gangxie112** [bufbuild/protovalidate-java#56]
## Description

tried to integrate protovalidate with my maven project:
        <dependency>
            <groupId>build.buf</groupId>
            <artifactId>protovalidate</artifactId>
            <version>0.1.6</version>
        </dependency>
And then import the validate.proto: import "buf/validate/validate.proto";

When compiling, a lot of waring of "Explicit 'optional' labels are disallowed in the Proto3 syntax", and finally the the error "Import "buf/validate/validate.proto" was not found or had errors".

## Environment

- **Operating System**: 
- **Version**: 
- **Compiler/Toolchain**: 
- **Protobuf Compiler & Version**: 
- **Protoc-gen-validate Version**: 
- **Protovalidate Version**:

**Comment by pkwarren** [comment]
Which version of protoc do you have installed? The "Explicit 'optional' labels are disallowed in the Proto3 syntax" error points to a version prior to 3.15.0, where the optional label is allowed by default. See https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3 for more details.

**Comment by pkwarren** [comment]
Going to close out this issue for now. I'd recommend updating protoc to a newer version that supports proto3 optionals.
