### ISSUE TITLE
[BUG] Uniqueness only works on lists of primitive values

### ISSUE THREAD

**Issue by mivanovcpd** [bufbuild/protovalidate-java#63]
## Description
Messages in `Protobuf` have overridden equals method so they can usually be compared correctly.
Suppose we have the following:
```
message Person {
  optional string name = 1 [(buf.validate.field).required = true];
  optional string family = 2 [(buf.validate.field).required = true];
}
message Persons {
  repeated PersonName persons = 1 [(buf.validate.field).repeated.unique = true];
}
```

## Steps to Reproduce
1. Create the relevant `proto` file as described above and write a test to validate a message from the generated model.

## Expected Behavior
The validation should work.

## Actual Behavior
The validation fails because the `protovalidate-java` doesn't support unique constraint on non-primitive types.

## Environment

- **Operating System**: Linux
- **Version**: Mint
- **Compiler/Toolchain**: Kotlin
- **Protovalidate Version**:  0.1.8

## Possible Solution
Disable the restriction in the code and allow arbitrary things to be compared to ensure uniqueness.

**Comment by pkwarren** [comment]
This is documented in the validate schema and not specific to the Java implementation: https://github.com/bufbuild/protovalidate/blob/7c3e2e3847b75e892b49411c788c350c5e272288/proto/protovalidate/buf/validate/validate.proto#L3316-L3318

There is a similar but not identical issue reported upstream in the protovalidate repo: https://github.com/bufbuild/protovalidate/issues/92. I'd suggest opening a feature request there as any changes would need to be first made there, then verified in conformance tests, and then make their way to all of the language implementations.
