### ISSUE TITLE
[BUG] Unable to find dependency `build.buf.gen:bufbuild_protovalidate_protocolbuffers_java:jar:23.4.0.1.20230711201221.890d7e3584ce`

### ISSUE THREAD

**Issue by katherine-signal** [bufbuild/protovalidate-java#8]
## Description
I'm trying to install `protovalidate-java` in my Maven project, but I'm running into an error resolving its dependencies: 

```
Could not find artifact build.buf.gen:bufbuild_protovalidate_protocolbuffers_java:jar:23.4.0.1.20230711201221.890d7e3584ce in central (https://repo.maven.apache.org/maven2)
```

When I navigate to the [Maven search engine](https://central.sonatype.com/artifact/build.buf/protovalidate/0.0.1/dependencies), I see that the component `bufbuild_protovalidate_protocolbuffers_java` "has not completed ingestion", which sounds like it hasn't yet been uploaded to the Maven central repository. 

## Steps to Reproduce
In a Maven project, add this snippet to the pom file:
```
<dependency>
    <groupId>build.buf</groupId>
    <artifactId>protovalidate</artifactId>
    <version>0.0.1</version>
</dependency>
```
then attempt to install dependencies with `mvn clean generate-sources`

## Expected Behavior

The `mvn` command completes without errors.

## Actual Behavior

I get:

```
[ERROR] ... Could not find artifact build.buf.gen:bufbuild_protovalidate_protocolbuffers_java:jar:23.4.0.1.20230711201221.890d7e3584ce in central (https://repo.maven.apache.org/maven2)
```

## Environment

- **Operating System**: macOS
- **Version**: macOS 13.4.1 
- **Compiler/Toolchain**: javac 17.0.5
- **Protobuf Compiler & Version**: libprotoc 23.4
- **Protoc-gen-validate Version**: 
- **Protovalidate Version**: 0.0.1

**Comment by mryan321** [comment]
i fixed this by adding to my repositories (https://buf.build/blog/maven-repository/):

```
 maven {
        url = uri("https://buf.build/gen/maven")
    }
```

**Comment by elliotmjackson** [comment]
solved by https://github.com/bufbuild/protovalidate-java/pull/13
